CREATE TABLE ADMIN(AID VARCHAR(7) PRIMARY KEY NOT NULL, ANAME VARCHAR(14));
CREATE TABLE DEPT(DID VARCHAR(7) PRIMARY KEY NOT NULL, DNAME VARCHAR(40), AID VARCHAR(7), FOREIGN KEY(AID) REFERENCES ADMIN(AID));
CREATE TABLE LECT(LID VARCHAR(7) PRIMARY KEY NOT NULL, LNAME VARCHAR(15), LEMAIL VARCHAR(30), LSALARY NUMERIC(10), DID VARCHAR(7), FOREIGN KEY(DID) REFERENCES DEPT(DID));
CREATE TABLE COURSE(CID VARCHAR(7) PRIMARY KEY NOT NULL, CNAME VARCHAR(20), DID VARCHAR(7), FOREIGN KEY(DID) REFERENCES DEPT(DID));
CREATE TABLE MODULE(MID VARCHAR(7) PRIMARY KEY NOT NULL, MNAME VARCHAR(20), CID VARCHAR(7), LID VARCHAR(7), FOREIGN KEY(CID) REFERENCES COURSE(CID), FOREIGN KEY(LID) REFERENCES LECT(LID));
CREATE TABLE STUDENT(SID VARCHAR(10) PRIMARY KEY NOT NULL, SNAME VARCHAR(20), SPHONE NUMERIC(10), SDOB DATE NOT NULL, SADD VARCHAR(20), AID VARCHAR(7), CID VARCHAR(7),FOREIGN KEY(AID) REFERENCES ADMIN(AID),FOREIGN KEY(CID) REFERENCES COURSE(CID));
CREATE TABLE MODULE_STUDENT(MID VARCHAR(7),SID VARCHAR(7), PRIMARY KEY(MID,SID),FOREIGN KEY(MID) REFERENCES MODULE(MID),FOREIGN KEY(SID) REFERENCES STUDENT(SID) );
ALTER TABLE MODULE
MODIFY MNAME varchar(40);

SELECT * FROM STUDENT WHERE SNAME='NIKITHA REDDY' and SDOB='2000-06-15';
SELECT * FROM LECT WHERE LSALARY>=80000;

SELECT SADD,COUNT(*) FROM STUDENT GROUP BY SADD;
SELECT DID,SUM(LSALARY),MAX(LSALARY),MIN(LSALARY),AVG(LSALARY) FROM LECT GROUP BY DID;

SELECT LID, LNAME, LECT.DID, DNAME FROM LECT INNER JOIN DEPT ON
LECT.DID=DEPT.DID;
SELECT CID, CNAME, COURSE.DID, DNAME FROM COURSE INNER JOIN DEPT ON
COURSE.DID=DEPT.DID;

SELECT * FROM STUDENT LEFT JOIN COURSE ON STUDENT.CID=COURSE.CID ORDER BY COURSE.CNAME;
SELECT * FROM MODULE LEFT JOIN LECT ON MODULE.LID=LECT.LID ORDER BY LECT.LNAME;
SELECT * FROM COURSE RIGHT JOIN DEPT ON COURSE.DID=DEPT.DID ORDER BY DEPT.DNAME;

SELECT SNAME,CNAME FROM STUDENT,COURSE WHERE STUDENT.CID=COURSE.CID;
SELECT LNAME,DNAME FROM LECT,DEPT WHERE LECT.DID=DEPT.DID;
SELECT LNAME FROM LECT WHERE DID='D001' UNION SELECT LNAME FROM LECT WHERE DID='D002';
SELECT LNAME,LSALARY FROM LECT WHERE DID='D005' UNION SELECT LNAME,LSALARY FROM LECT WHERE DID='D010';
SELECT DNAME ,count(LID) FROM LECT,DEPT WHERE LECT.DID=DEPT.DID group by DNAME;




